name: Quality pipeline

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"

jobs:
  quality_pipeline:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
